baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Cibercueva'

[permalinks]
  blog = "/:filename/"
  
[taxonomies]
  tag = "tags"

[params]
  homeText = "Bienvenido a mi página web personal! Aquí pongo artículos sobre mis hobbies, fotos de mis miniaturas, historietas que escribo, o cualquier otra cosa que se me ocurra! Espero que encuentres algo que te parezca interesante..."

[menu]
  [[menu.main]]
    name = "Wargaming"
    url = "/wargaming/"
    weight = 1
  [[menu.main]]
    name = "Recetas"
    url = "/recetas/"
    weight = 2
  [[menu.main]]
    name = "Relatos"
    url = "/relatos/"
    weight = 3
   [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4
